### ISSUE TITLE
Moodle Coding guidelines

### ISSUE THREAD

**Issue by danmarsden** [kamat/mcae#20]
I'm looking at using your plugin for a project I'm working on - first thing we do is check a plugin to see how well it complies with Moodle's normal coding guidelines - looks like there are a few superficial issues with whitespaces (tabs instead of spaces) and a few other issues. Github integrates really well with a tool called Travis CI which is capable of running a range of automatic tests on your code including Moodle coding guidelines, Behat/Unit tests on multiple versions of PHP - I'll send through a pull request so you can add this to your main repository and see the results but in the meantime you can see the results from my repository here:
https://travis-ci.org/danmarsden/mcae

on that page you will see 8 different reports using a different combination of Moodle branch (3.0/master), Database version and PHP version. (this combination is configurable by modifying the .travis.yml file in that branch)

There's also a great post from David Mudrak in the forums with a lot more detail:
https://moodle.org/mod/forum/discuss.php?d=323384

I may also submit a pull request to address some of the "errors" in the reports as well. Hope you find it useful.

**Comment by kamat** [comment]
Thanks for your pull request.
I fix plugin and now all 8 test are green.
https://travis-ci.org/kamat/moodle-auth_mcae

Also I rename repository to "moodle-auth_mcae" as required by the repository naming convention for Moodle plugins.

**Comment by danmarsden** [comment]
wow - great work! :-)
