### ISSUE TITLE
Moodle 2.7 deprecation notices

### ISSUE THREAD

**Issue by silent-e** [kamat/mcae#7]
Is there any movement on upgrading this to fully support Moodle 2.7?  I'm seeing deprecation notices like …

* get_context_instance() is deprecated, please use context_xxxx::instance() instead.
* add_to_log in the auth.php file is also deprecated.

These don't appear to be that hard to fix and I may submit a pull request but thought I'd ask first.

It appears that the plugin still works for now.  Thanks in advance.

(e)

**Comment by silent-e** [comment]
Thanks for the update fixing the context calls.  However after [this commit](https://github.com/kamat/mcae/commit/2fbf8feda1200c6ce3e38b38cb2c2ba4126c2e1e) it isn't usable in Moodle 2.7 because you've specified the required version as 2014110400.  I've just upgraded our Moodle install to 2.7.5+ (Build 20151212) and its version is 2014051205.02.

Is this plugin compatible in 2.7?

**Comment by kamat** [comment]
This plugin still compatible in 2.7. Requirements changed. [commit](https://github.com/kamat/mcae/commit/42fcd45c9023fff81a1d81a53a310542979867af)

**Comment by silent-e** [comment]
Thanks.
